import type { Congratulation, Stats, Student } from '@/types'

export function generateMemoryBookHtml(
  student: Student,
  wishes: Congratulation[],
  stats: Stats,
): string {
  const wishRows = wishes
    .map(
      (w) => `
      <div class="wish">
        <div class="wish-header">
          <strong>${escapeHtml(w.senderName)}</strong>
          <span>${w.createdAt.toLocaleDateString('ar-SA')}</span>
        </div>
        <p>${escapeHtml(w.message)}</p>
        ${w.isPinned ? '<span class="pin">📌 مثبتة</span>' : ''}
      </div>`,
    )
    .join('')

  return `<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
  <meta charset="UTF-8"/>
  <title>ذكريات التخرج — ${escapeHtml(student.name)}</title>
  <style>
    body { font-family: 'Segoe UI', Tahoma, sans-serif; background: #faf8f5; color: #2c2825; padding: 40px; max-width: 800px; margin: 0 auto; }
    h1 { color: #a68b4b; border-bottom: 2px solid #c9a962; padding-bottom: 12px; }
    .profile { display: flex; gap: 20px; align-items: center; margin: 24px 0; }
    .profile img { width: 100px; height: 100px; border-radius: 50%; object-fit: cover; border: 3px solid #c9a962; }
    .stats { display: grid; grid-template-columns: repeat(2, 1fr); gap: 12px; margin: 24px 0; }
    .stat { background: white; padding: 16px; border-radius: 12px; border: 1px solid #ede8df; text-align: center; }
    .stat strong { display: block; font-size: 24px; color: #c9a962; }
    .wish { background: white; padding: 20px; border-radius: 12px; margin: 12px 0; border: 1px solid #ede8df; }
    .wish-header { display: flex; justify-content: space-between; margin-bottom: 8px; color: #8a8279; font-size: 14px; }
    .pin { color: #c9a962; font-size: 12px; }
    @media print { body { padding: 20px; } }
  </style>
</head>
<body>
  <h1>🎓 ذكريات التخرج</h1>
  <div class="profile">
    <img src="${student.profileImage}" alt="${escapeHtml(student.name)}"/>
    <div>
      <h2>${escapeHtml(student.name)}</h2>
      <p>${escapeHtml(student.university)} — ${escapeHtml(student.major)}</p>
      <p>تخرج ${student.graduationYear}</p>
    </div>
  </div>
  <div class="stats">
    <div class="stat"><strong>${stats.totalCongratulations}</strong> تهنئة</div>
    <div class="stat"><strong>${stats.totalVisitors}</strong> زائر</div>
    <div class="stat"><strong>${stats.photosShared}</strong> صورة</div>
    <div class="stat"><strong>${stats.todaysWishes}</strong> تهنئة اليوم</div>
  </div>
  <h2>رسائل التهنئة</h2>
  ${wishRows || '<p>لا توجد رسائل بعد</p>'}
  <footer style="margin-top:40px;text-align:center;color:#8a8279;font-size:12px;">
    Generated by Congrats Platform — ${new Date().toLocaleDateString('ar-SA')}
  </footer>
</body>
</html>`
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

export function downloadMemoryBook(html: string, filename: string) {
  const blob = new Blob([html], { type: 'text/html;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}
